export const PUSH_ACCOUNT = 'push_account'
export const GET_CLASS_LIST = 'get_class_list'
export const GET_TEA_CLASS_LIST = 'get_tea_class_list'
export const GET_TALKINGS = 'get_talkings'  //获取讨论列表
export const GET_ANCE = 'get_ance' //获取公告
export const GET_VIDEO_LIST = 'get_video_list'  //获取视屏列表
export const GET_HOMEWORK_LIST = 'get_homework_list'  //获取作业列表
export const USER_SIGN_OUT = 'user_sign_out'  //退出登陆
export const GET_STU_LIST = 'get_stu_list'  //获取学生列表
export const GET_MEG_CLASS_LIST = 'getMegClassList'  //获取班级管理列表